// @ts-nocheck -- skip type checking
import * as docs_6 from "../src/content/docs/guide/workspace-privacy.mdx?collection=docs&hash=1775308113071"
import * as docs_5 from "../src/content/docs/guide/welcome.mdx?collection=docs&hash=1775308113071"
import * as docs_4 from "../src/content/docs/guide/troubleshooting.mdx?collection=docs&hash=1775308113071"
import * as docs_3 from "../src/content/docs/guide/models.mdx?collection=docs&hash=1775308113071"
import * as docs_2 from "../src/content/docs/guide/get-started.mdx?collection=docs&hash=1775308113071"
import * as docs_1 from "../src/content/docs/guide/for-developers.mdx?collection=docs&hash=1775308113071"
import * as docs_0 from "../src/content/docs/guide/chat.mdx?collection=docs&hash=1775308113071"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"guide/chat.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/chat.mdx"}, data: docs_0 }, { info: {"path":"guide/for-developers.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/for-developers.mdx"}, data: docs_1 }, { info: {"path":"guide/get-started.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/get-started.mdx"}, data: docs_2 }, { info: {"path":"guide/models.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/models.mdx"}, data: docs_3 }, { info: {"path":"guide/troubleshooting.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/troubleshooting.mdx"}, data: docs_4 }, { info: {"path":"guide/welcome.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/welcome.mdx"}, data: docs_5 }, { info: {"path":"guide/workspace-privacy.mdx","absolutePath":"/Users/sudhanshutiwary/Desktop/Projects/Viper AI/ViperAI/apps/web-app/src/content/docs/guide/workspace-privacy.mdx"}, data: docs_6 }], [])